version: '3'

services:
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/.
        image: mariadb
        volumes: 
            - db_data:/var/lib/mysql/
        restart: always
        networks:
            - wp
        env_file: .env
    
    wordpress:
        depends_on: 
            - mariadb
        container_name: wordpress
        build: ./requirements/wordpress/.
        image: wordpress
        volumes: 
            - wp_data:/var/www/
        restart: always
        networks: 
            - wp
        env_file: .env

    nginx:
        depends_on: 
            - mariadb
            - wordpress
        container_name: nginx
        image: nginx
        build: ./requirements/nginx/.
        restart: always
        networks:
            - wp
        ports:
            - 443:443
        volumes:
            - wp_data:/var/www/

#Ces containers sont des bonus
    adminer:
        container_name: adminer
        image: adminer
        build: ./requirements/bonus/adminer/.
        restart: always
        networks: 
            - wp
        depends_on: 
            - mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
    
    ftp:
        container_name: ftp
        image: ftp
        build: ./requirements/bonus/ftp/.
        restart: always
        ports:
            - 21000-21010:21000-21010
            - 21:21
            - 20:20
        networks:
            - wp
        volumes:
            - wp_data:/home/ftp
        env_file: ./requirements/bonus/ftp/conf/.envftp

    # redis:
    #     container_name: redis
    #     depends_on:
    #         - wordpress
    #     image: redis
    #     build: ./requirements/bonus/redis/.
    #     restart: always
    #     networks:
    #         - wp

networks: 
    wp:

volumes:
    wp_data:
        driver: local
        driver_opts: 
            type: 'none'
            o: 'bind'
            device: '/home/gtaverne/data/static'
    db_data:
        driver: local
        driver_opts: 
            type: 'none'
            o: 'bind'
            device: '/home/gtaverne/data/db'
    jupy_vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/gtaverne/data/jupyter'